Allow distribute scala 2.12 and update to spark 2.4.3
elastic/elasticsearch-hadoop pull request #1308
Opened 2019-06-22 12:49 UTC by neoramon

What do you think about distributing Elasticsearch spark" in Scala 2.12 as well?

2019-06-22 12:49 UTC, elasticcla commented
Hi @neoramon, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/elastic/elasticsearch-hadoop/pull/1308.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

2019-06-22 13:10 UTC, neoramon commented
[Please_DocuSign_Individual_Contributor_Licen (1).pdf](https://github.com/elastic/elasticsearch-hadoop/files/3316847/Please_DocuSign_Individual_Contributor_Licen.1.pdf)

2019-08-23 20:42 UTC, jbaiera commented
Sorry for the wait on this issue folks. I'll look into getting this tested and reviewed soon. The way we cross compile Scala in the build has been up in the air for a while due to some external forces on the project (mostly needing to upgrade our version of Gradle, but that upgrade broke our Scala cross compile stuff). Now that the concerns around our compile logic are clearing up, we can start looking at this in earnest.

2019-11-06 18:56 UTC, EmergentOrder commented
@jbaiera Any update here?

2019-11-23 13:42 UTC, f1yegor commented on gradle.properties
> +scala212Version = 2.12.8
2.12.10 is the most recent

2019-11-25 10:04 UTC, f1yegor commented
@neoramon @jbaiera any update on the issue? do you need any help? 
current MR has a conflict that is easy to merge into master. 

I will build with 2.12 locally because I depend on it for my project, feel free to ask for some fixes to end it in master.

2019-11-26 16:16 UTC, neoramon commented on gradle.properties
> +scala212Version = 2.12.8
Ok, I will change.

2019-11-27 21:08 UTC, neoramon commented
Done

2019-12-09 21:17 UTC, fistan684 commented
Any updates? Looks like it's almost there. :)

2019-12-10 12:14 UTC, neoramon commented
> At least Java 11 is required to use elasticsearch gradle tools

It seems that Travis doesn't have Java 11 config.

2019-12-10 13:49 UTC, f1yegor commented
> > At least Java 11 is required to use elasticsearch gradle tools
> 
> It seems that Travis doesn't have Java 11 config.

I would ask the legitimacy of that move (java 8 -> java 11) for build, up to my knowledge spark(2.4, i haven't dig into 3.0 topic yet) doesn't explicitly support java 11.

2019-12-10 13:58 UTC, neoramon commented
> > > At least Java 11 is required to use elasticsearch gradle tools
> > 
> > 
> > It seems that Travis doesn't have Java 11 config.
> 
> I would ask the legitimacy of that move (java 8 -> java 11) for build, up to my knowledge spark(2.4, i haven't dig into 3.0 topic yet) doesn't explicitly support java 11.

I'm not sure why this build needs java 11, there is a validation on build for Java >= 11.
```
buildSrc/build.gradle
if (JavaVersion.current() < JavaVersion.VERSION_11) {
    throw new GradleException('At least Java 11 is required to use elasticsearch gradle tools')
}
```

At the end, it also needs Java 8 for hadoop. 
And I don't know how to set two jdk in travis.

:(

2019-12-10 21:26 UTC, jbaiera commented
@neoramon I share your confusion on the Travis CI situation. I've tried a number of configurations and none of them have panned out. We are working on changing the CI for the project to use the public Jenkins builds for the CI checks instead.

As for the reasoning behind the move to Java 11+ for the build: We use the Elasticsearch project Gradle build tools to stand up clusters for our testing. In order to stay in sync with the versions of the build tools (which only support Java 12), we need the build to run on that same version of Java. That said, we still need Java 8 in an environment variable in order to compile Scala with the correct versions.

2020-01-01 00:07 UTC, cdmitri commented
👍  @neoramon @jbaiera - thank you for working on this!

I've compiled on jdk8 and scala 2.12.10 with basic app tests passing. Just the src code changes (I was half way though before I found this PR ;)

Dataproc on GCP image preview is 2.12 now, so this is becoming more critical - adding my +1 here

@neoramon - thank you for the PR!

2020-02-05 17:42 UTC, rlmark commented
Hi there! Any updates on this? Is there any way to help? Thanks for your work on this issue so far! 😄

2020-02-06 23:22 UTC, cdmitri commented
> Hi there! Any updates on this? Is there any way to help? Thanks for your work on this issue so far! 😄

@rlmark  - I'm watching this as well, here is the latest relevant comment: https://github.com/elastic/elasticsearch-hadoop/issues/1412#issuecomment-579464498

2020-02-07 19:03 UTC, jbaiera commented
Hi all, a quick update here: I've logged an [issue](https://github.com/elastic/elasticsearch-hadoop/issues/1423) on the project pertaining to our growing pains with building Scala. This PR will most likely need to wait for that issue to be resolved before it can be moved any further.

2020-04-09 12:05 UTC, Habitats commented
Do you have a rough timeline for when you think these things will happen @jbaiera? 

And, is it possible to hack this together by building some of the parts myself?

2020-07-01 21:57 UTC, rex-remind101 commented
Any updates on this?

2020-07-01 22:41 UTC, rex-remind101 commented
@neoramon i'm trying to build your fork locally https://github.com/neoramon/elasticsearch-hadoop and it seems to fail with
```
> Task :buildSrc:compileGroovy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:compileGroovy'.
> Compilation failed; see the compiler error output for details.
```
please help?

2020-09-24 16:06 UTC, ktakanov commented
Any updates on this? /2

2020-09-24 17:19 UTC, neoramon commented
This is PR is old now and it will need an update from master. 
Someone know how to fix the problem of running Travis with two jdk?

2020-09-24 18:52 UTC, neoramon commented
I just did merge with master and saw that travis file was removed, and it looks that all checks have passed! 👍

2020-09-27 01:36 UTC, ktakanov commented
Ccan someone review and merge?

2020-10-26 12:10 UTC, adamczarny commented
Is there any news on when it'll be merged?

2020-10-28 19:54 UTC, LannyRipple requested changes

2020-10-28 19:54 UTC, LannyRipple commented on gradle.properties
> +scala212Version = 2.12.10
Latest Scala 2.12 version is now 2.12.12

2020-11-19 18:07 UTC, neoramon commented
I'm closing this PR.
@jbaiera already updated spark and scala version in this PR: https://github.com/elastic/elasticsearch-hadoop/pull/1551/files

2020-11-19 18:07 UTC, closed without merging

2020-11-22 15:16 UTC, vishnugs commented
Even im facing this issue with Spark 3.0 and no option to use scala 2.11 as spark supports min 2.12 onwards from 3.0.0